name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v7

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install packages
        working-directory: app
        run: npm ci

      - name: Disable Pulse tracking
        working-directory: app
        run: |
           rm -f public/config.json

      - name: Build app
        working-directory: app
        run: npm run build

      - name: Upload build
        uses: actions/upload-pages-artifact@v5
        with:
          path: app/dist

      - name: Deploy
        uses: actions/deploy-pages@v5
